"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$java\
$python\
$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
text = "#cdd6f4"
blue = "#89b4fa"
green = "#a6e3a1"
yellow = "#f9e2af"
red = "#f38ba8"
purple = "#cba6f7"

[os]
disabled = false
style = "bold blue"

[os.symbols]
NixOS = "󱄅 "

[username]
show_always = true
style_user = "bold green"
format = '[$user]($style) '

[directory]
style = "bold yellow"
format = "[$path]($style) "
truncation_length = 3

[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold red"

[nodejs]
symbol = " "
style = "bold green"
format = "[$symbol$version]($style) "

[java]
symbol = " "
style = "bold red"
format = "[$symbol$version]($style) "

[python]
symbol = " "
style = "bold yellow"
format = "[$symbol$version]($style) "

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
